baseURL: "https://zinzolin.org/projets/tmi"
defaultContentLanguage: "fr"
languageCode: "fr"
params:
    description: "Le site-école du master « Techniques des métiers de l’information »"
    featured: true
theme: "origin"
timeZone: "Europe/Paris"
title: "TMI"